# Generated by Django 3.1.12 on 2025-10-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='tags',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('advising', 'Adivising'), ('registration', 'Registration'), ('graduation', 'Graduation'), ('general', 'General Questions for CSEE Department'), ('csQuestions', 'Computer Science Program')], default='general', max_length=50),
        ),
    ]
